---
deployment:
  tasks:
    - export DEPLOYPATH=/home/clouksjx/public_html/
    # Stylesheets 
    - /bin/cp -R style $DEPLOYPATH
    # Pages
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH
    - /bin/cp projects-broken.html $DEPLOYPATH
    # Images
    - /bin/cp -R img $DEPLOYPATH