---
deployment:
  tasks:
    - export DEPLOYPATH=/home/clouksjx/public_html/
    - export REPOPATH=/home/clouksjx/repositories/personal-website/
    - $REPOPATH index.html $DEPLOYPATH
    - $REPOPATH style.css $DEPLOYPATH