---
deployment:
  tasks:
    - export DEPLOYPATH=/home/clouksjx/public_html/
    # Stylesheets 
    - /bin/cp -R style $DEPLOYPATH
    # Pages
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R articles $DEPLOYPATH
    - /bin/cp -R tutorials $DEPLOYPATH
    - /bin/cp -R apps $DEPLOYPATH
    # Images
    - /bin/cp -R img $DEPLOYPATH