---
deployment:
  tasks:
    - export DEPLOYPATH=/home/clouksjx/public_html/
    # Main files
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    # Other pages
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH
    # Images
    - /bin/cp -R img $DEPLOYPATH