[package]
name = "article-formatter"
version = "0.1.0"
authors = ["Tim <34661586+timjchandler@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"
